### ISSUE TITLE
ERRO CORS

### ISSUE THREAD

**Issue by iDaaniBooY** [cassiano-dio/cibersecurity-desafio-phishing#27]
![VirtualBox_Kali Linux_13_12_2023_20_05_32](https://github.com/cassiano-dio/cibersecurity-desafio-phishing/assets/141791338/6bba21a1-a2d1-47b3-8381-1639760d80fc)

**Comment by alexandrecunhajr** [comment]
Seguindo o default do sistema setoolkit , só funciona em navegadores antigos, tive sucesso testando no IE8  ou efetuar configurações corretas de CORS no template gerado.

Navegadores atuais tratam bem a questão de CORS.

**Comment by iDaaniBooY** [comment]
Fiz exatamente a mesma coisa, consegui no IE8, o CORS é realmente bem complexo
